baseURL = "https://AdriMota.github.io/Blog-LabVeilTech"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Laboratoire de veille technologique"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@zerostaticio"
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addDot = true
  addFrame = true
  highlightColor = '#B0ABAB'
  baseColor = "#EFEFEF"
  baseOffsetColor = "#eaeaea"
  headingColor = "#9C1E20"
  textColor = "#1D1D1F"
  dotColor = "#1D1D1F"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Accueil'
    url = '/'
    weight = 1
